# Generated by Django 4.2.2 on 2023-09-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='null', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
