# Generated by Django 4.2.5 on 2023-09-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lastView',
            new_name='date',
        ),
    ]
