# Generated by Django 4.2.5 on 2023-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
