# Generated by Django 4.2.5 on 2023-11-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.TextField(default='false'),
        ),
    ]
