# Generated by Django 4.2.5 on 2023-11-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_post_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
