# Generated by Django 4.2.5 on 2023-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='d', max_length=500),
            preserve_default=False,
        ),
    ]
