# Generated by Django 4.2.5 on 2023-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_websitemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemeta',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
