# Generated by Django 4.2.5 on 2023-12-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_post_bookmarks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarks_id',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
