# Generated by Django 4.2.5 on 2023-12-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_post_bookmarks_id_post_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
    ]
